# Generated by Django 3.0.5 on 2020-04-30 20:58

from django.db import migrations, models
import django.db.models.deletion
import utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', utils.fields.CurrencyField(choices=[('SEK', 'SEK'), ('EUR', 'EUR')], default=('SEK', 'SEK'), max_length=3)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Classified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('price', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classified', to='classifieds.Price')),
            ],
        ),
    ]
